import gluestackPlugin from "@gluestack-ui/nativewind-utils/tailwind-plugin";

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: "class",
	content: ["App.{tsx,jsx,ts,js}", "index.{tsx,jsx,ts,js}", "components/**/*.{tsx,jsx,ts,js}", "app/**/*.{tsx,jsx,ts,js}", "src/**/*.{tsx,jsx,ts,js}"],
	presets: [require("nativewind/preset")],
	safelist: [
		{
			pattern: /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background|indicator)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark|primary)/,
		},
	],
	theme: {
		extend: {
			colors: {
				text: {
					primary: "rgb(var(--text-primary)/<alpha-value>)",
					closed: "rgb(var(--text-closed)/<alpha-value>)",
					muted: "rgb(var(--text-muted)/<alpha-value>)",
					disabled: "rgb(var(--text-disabled)/<alpha-value>)",
					onDisabled: "rgb(var(--text-on-disabled)/<alpha-value>)",
				},
				bg: {
					app: "rgb(var(--bg-app)/<alpha-value>)",
					disabled: "rgb(var(--bg-disabled)/<alpha-value>)",
				},
				card: {
					bg: {
						open: "rgb(var(--bg-card-open)/<alpha-value>)",
						closed: "rgb(var(--bg-card-closed)/<alpha-value>)",
					},
					border: {
						open: "rgb(var(--border-card-open)/<alpha-value>)",
						closed: "rgb(var(--border-card-closed)/<alpha-value>)",
					},
					pressable: {
						default: "rgb(var(--bg-pressable)/<alpha-value>)",
						pressed: "rgb(var(--bg-pressable-pressed)/<alpha-value>)",
						closed: {
							default: "rgb(var(--bg-pressable-closed)/<alpha-value>)",
							pressed: "rgb(var(--bg-pressable-closed-pressed)/<alpha-value>)",
						},
					},
				},
				favorite: {
					bg: {
						default: "rgb(var(--bg-favorite)/<alpha-value>)",
						pressed: "rgb(var(--bg-favorite-pressed)/<alpha-value>)",
						pinned: {
							default: "rgb(var(--bg-favorite-pinned)/<alpha-value>)",
							pressed: "rgb(var(--bg-favorite-pinned-pressed)/<alpha-value>)",
						},
					},
					icon: {
						default: "rgb(var(--icon-favorite)/<alpha-value>)",
						pinned: "rgb(var(--icon-favorite-pinned)/<alpha-value>)",
					},
				},
				parkStatus: {
					bg: {
						open: "rgb(var(--bg-park-status-open)/<alpha-value>)",
						closed: "rgb(var(--bg-park-status-closed)/<alpha-value>)",
					},
					onBg: {
						open: "rgb(var(--on-bg-park-status-open)/<alpha-value>)",
						closed: "rgb(var(--on-bg-park-status-closed)/<alpha-value>)",
					},
				},
				rideStatus: {
					bg: {
						highWait: "rgb(var(--bg-ride-status-high-wait)/<alpha-value>)",
						mediumWait: "rgb(var(--bg-ride-status-medium-wait)/<alpha-value>)",
						lowWait: "rgb(var(--bg-ride-status-low-wait)/<alpha-value>)",
						closed: "rgb(var(--bg-ride-status-closed)/<alpha-value>)",
						maintenance: "rgb(var(--bg-ride-status-maintenance)/<alpha-value>)",
					},
					border: {
						highWait: "rgb(var(--border-ride-status-high-wait)/<alpha-value>)",
						mediumWait: "rgb(var(--border-ride-status-medium-wait)/<alpha-value>)",
						lowWait: "rgb(var(--border-ride-status-low-wait)/<alpha-value>)",
						closed: "rgb(var(--border-ride-status-closed)/<alpha-value>)",
						maintenance: "rgb(var(--border-ride-status-maintenance)/<alpha-value>)",
					},
					onBg: {
						highWait: "rgb(var(--on-bg-ride-status-high-wait)/<alpha-value>)",
						mediumWait: "rgb(var(--on-bg-ride-status-medium-wait)/<alpha-value>)",
						lowWait: "rgb(var(--on-bg-ride-status-low-wait)/<alpha-value>)",
						closed: "rgb(var(--on-bg-ride-status-closed)/<alpha-value>)",
						maintenance: "rgb(var(--on-bg-ride-status-maintenance)/<alpha-value>)",
					},
				},

				primary: {
					50: "rgb(var(--color--primary-50)/<alpha-value>)",
					100: "rgb(var(--color--primary-100)/<alpha-value>)",
					200: "rgb(var(--color--primary-200)/<alpha-value>)",
					300: "rgb(var(--color--primary-300)/<alpha-value>)",
					400: "rgb(var(--color--primary-400)/<alpha-value>)",
					500: "rgb(var(--color--primary-500)/<alpha-value>)",
					600: "rgb(var(--color--primary-600)/<alpha-value>)",
					700: "rgb(var(--color--primary-700)/<alpha-value>)",
					800: "rgb(var(--color--primary-800)/<alpha-value>)",
					900: "rgb(var(--color--primary-900)/<alpha-value>)",
					950: "rgb(var(--color--primary-950)/<alpha-value>)",
				},
				secondary: {
					50: "rgb(var(--color--secondary-50)/<alpha-value>)",
					100: "rgb(var(--color--secondary-100)/<alpha-value>)",
					200: "rgb(var(--color--secondary-200)/<alpha-value>)",
					300: "rgb(var(--color--secondary-300)/<alpha-value>)",
					400: "rgb(var(--color--secondary-400)/<alpha-value>)",
					500: "rgb(var(--color--secondary-500)/<alpha-value>)",
					600: "rgb(var(--color--secondary-600)/<alpha-value>)",
					700: "rgb(var(--color--secondary-700)/<alpha-value>)",
					800: "rgb(var(--color--secondary-800)/<alpha-value>)",
					900: "rgb(var(--color--secondary-900)/<alpha-value>)",
					950: "rgb(var(--color--secondary-950)/<alpha-value>)",
				},
				accent: {
					50: "rgb(var(--color--accent-50)/<alpha-value>)",
					100: "rgb(var(--color--accent-100)/<alpha-value>)",
					200: "rgb(var(--color--accent-200)/<alpha-value>)",
					300: "rgb(var(--color--accent-300)/<alpha-value>)",
					400: "rgb(var(--color--accent-400)/<alpha-value>)",
					500: "rgb(var(--color--accent-500)/<alpha-value>)",
					600: "rgb(var(--color--accent-600)/<alpha-value>)",
					700: "rgb(var(--color--accent-700)/<alpha-value>)",
					800: "rgb(var(--color--accent-800)/<alpha-value>)",
					900: "rgb(var(--color--accent-900)/<alpha-value>)",
					950: "rgb(var(--color--accent-950)/<alpha-value>)",
				},
				"high-wait-time": {
					50: "rgb(var(--color--high-wait-time-50)/<alpha-value>)",
					100: "rgb(var(--color--high-wait-time-100)/<alpha-value>)",
					200: "rgb(var(--color--high-wait-time-200)/<alpha-value>)",
					300: "rgb(var(--color--high-wait-time-300)/<alpha-value>)",
					400: "rgb(var(--color--high-wait-time-400)/<alpha-value>)",
					500: "rgb(var(--color--high-wait-time-500)/<alpha-value>)",
					600: "rgb(var(--color--high-wait-time-600)/<alpha-value>)",
					700: "rgb(var(--color--high-wait-time-700)/<alpha-value>)",
					800: "rgb(var(--color--high-wait-time-800)/<alpha-value>)",
					900: "rgb(var(--color--high-wait-time-900)/<alpha-value>)",
					950: "rgb(var(--color--high-wait-time-950)/<alpha-value>)",
				},
				error: {
					50: "rgb(var(--color--error-50)/<alpha-value>)",
					100: "rgb(var(--color--error-100)/<alpha-value>)",
					200: "rgb(var(--color--error-200)/<alpha-value>)",
					300: "rgb(var(--color--error-300)/<alpha-value>)",
					400: "rgb(var(--color--error-400)/<alpha-value>)",
					500: "rgb(var(--color--error-500)/<alpha-value>)",
					600: "rgb(var(--color--error-600)/<alpha-value>)",
					700: "rgb(var(--color--error-700)/<alpha-value>)",
					800: "rgb(var(--color--error-800)/<alpha-value>)",
					900: "rgb(var(--color--error-900)/<alpha-value>)",
					950: "rgb(var(--color--error-950)/<alpha-value>)",
				},
				success: {
					50: "rgb(var(--color--success-50)/<alpha-value>)",
					100: "rgb(var(--color--success-100)/<alpha-value>)",
					200: "rgb(var(--color--success-200)/<alpha-value>)",
					300: "rgb(var(--color--success-300)/<alpha-value>)",
					400: "rgb(var(--color--success-400)/<alpha-value>)",
					500: "rgb(var(--color--success-500)/<alpha-value>)",
					600: "rgb(var(--color--success-600)/<alpha-value>)",
					700: "rgb(var(--color--success-700)/<alpha-value>)",
					800: "rgb(var(--color--success-800)/<alpha-value>)",
					900: "rgb(var(--color--success-900)/<alpha-value>)",
					950: "rgb(var(--color--success-950)/<alpha-value>)",
				},
			},
			fontFamily: {
				heading: ["Bebas Neue Pro", "sans-serif"],
				subheading: ["Bebas Neue Pro", "sans-serif"],
				body: ["Noto Sans", "sans-serif"],
			},
			boxShadow: {
				"hard-1": "-2px 2px 8px 0px rgba(38, 38, 38, 0.20)",
				"hard-2": "0px 3px 10px 0px rgba(38, 38, 38, 0.20)",
				"hard-3": "2px 2px 8px 0px rgba(38, 38, 38, 0.20)",
				"hard-4": "0px -3px 10px 0px rgba(38, 38, 38, 0.20)",
				"hard-5": "0px 2px 10px 0px rgba(38, 38, 38, 0.10)",
				"soft-1": "0px 0px 10px rgba(38, 38, 38, 0.1)",
				"soft-2": "0px 0px 20px rgba(38, 38, 38, 0.2)",
				"soft-3": "0px 0px 30px rgba(38, 38, 38, 0.1)",
				"soft-4": "0px 0px 40px rgba(38, 38, 38, 0.1)",
			},
		},
	},
	plugins: [gluestackPlugin],
};
