export const getParkImage = (id: string) => {
	try {
		const imageMap: Record<string, any> = {
			altontowers: require("../../assets/images/parks/park_altontowers.webp"),
			bobbejaanland: require("../../assets/images/parks/park_bobbejaanland.webp"),
			caribeaquaticpark: require("../../assets/images/parks/park_caribeaquaticpark.webp"),
			chessingtonworld: require("../../assets/images/parks/park_chessingtonworld.webp"),
			disneyadventureworld: require("../../assets/images/parks/park_disneyadventureworld.webp"),
			disneycaliforniaadventurepark: require("../../assets/images/parks/park_disneycaliforniaadventurepark.webp"),
			disneylandparis: require("../../assets/images/parks/park_disneylandparis.webp"),
			disneylandpark: require("../../assets/images/parks/park_disneylandpark.webp"),
			disneysanimalkingdomthemepark: require("../../assets/images/parks/park_disneysanimalkingdomthemepark.webp"),
			disneyshollywoodstudios: require("../../assets/images/parks/park_disneyshollywoodstudios.webp"),
			djurssommerland: require("../../assets/images/parks/park_djurssommerland.webp"),
			efteling: require("../../assets/images/parks/park_efteling.webp"),
			energylandia: require("../../assets/images/parks/park_energylandia.webp"),
			epcot: require("../../assets/images/parks/park_epcot.webp"),
			europapark: require("../../assets/images/parks/park_europapark.webp"),
			familypark: require("../../assets/images/parks/park_familypark.webp"),
			ferrariland: require("../../assets/images/parks/park_ferrariland.webp"),
			futuroscope: require("../../assets/images/parks/park_futuroscope.webp"),
			gardaland: require("../../assets/images/parks/park_gardaland.webp"),
			hansapark: require("../../assets/images/parks/park_hansapark.webp"),
			heidepark: require("../../assets/images/parks/park_heidepark.webp"),
			holidaypark: require("../../assets/images/parks/park_holidaypark.webp"),
			legoland: require("../../assets/images/parks/park_legoland.webp"),
			legolandbillund: require("../../assets/images/parks/park_legolandbillund.webp"),
			legolandcalifornia: require("../../assets/images/parks/park_legolandcalifornia.webp"),
			legolandflorida: require("../../assets/images/parks/park_legolandflorida.webp"),
			legolandnewyork: require("../../assets/images/parks/park_legolandnewyork.webp"),
			legolandwindsor: require("../../assets/images/parks/park_legolandwindsor.webp"),
			liseberg: require("../../assets/images/parks/park_liseberg.webp"),
			magickingdompark: require("../../assets/images/parks/park_magickingdompark.webp"),
			movieparkgermany: require("../../assets/images/parks/park_movieparkgermany.webp"),
			nigloland: require("../../assets/images/parks/park_nigloland.webp"),
			parcasterix: require("../../assets/images/parks/park_parcasterix.webp"),
			phantasialand: require("../../assets/images/parks/park_phantasialand.webp"),
			plopsalanddepanne: require("../../assets/images/parks/park_plopsalanddepanne.webp"),
			portaventurapark: require("../../assets/images/parks/park_portaventurapark.webp"),
			rulantica: require("../../assets/images/parks/park_rulantica.webp"),
			thorpepark: require("../../assets/images/parks/park_thorpepark.webp"),
			toverland: require("../../assets/images/parks/park_toverland.webp"),
			traumatica: require("../../assets/images/parks/park_traumatica.webp"),
			universalepicuniverse: require("../../assets/images/parks/park_universalepicuniverse.webp"),
			universalislandsofadventure: require("../../assets/images/parks/park_universalislandsofadventure.webp"),
			universalstudiosflorida: require("../../assets/images/parks/park_universalstudiosflorida.webp"),
			walibibelgium: require("../../assets/images/parks/park_walibibelgium.webp"),
			walibiholland: require("../../assets/images/parks/park_walibiholland.webp"),
		};
		return imageMap[id] || null;
	} catch (e) {
		return null;
	}
};

export const getParkHeaderImage = (id: string) => {
	try {
		const headerImageMap: Record<string, any> = {
			altontowers: require("../../assets/images/parks/header/park-header_altontowers.webp"),
			bobbejaanland: require("../../assets/images/parks/header/park-header_bobbejaanland.webp"),
			caribeaquaticpark: require("../../assets/images/parks/header/park-header_caribeaquaticpark.webp"),
			chessingtonworld: require("../../assets/images/parks/header/park-header_chessingtonworld.webp"),
			disneyadventureworld: require("../../assets/images/parks/header/park-header_disneyadventureworld.webp"),
			disneycaliforniaadventurepark: require("../../assets/images/parks/header/park-header_disneycaliforniaadventurepark.webp"),
			disneylandparis: require("../../assets/images/parks/header/park-header_disneylandparis.webp"),
			disneylandpark: require("../../assets/images/parks/header/park-header_disneylandpark.webp"),
			disneysanimalkingdomthemepark: require("../../assets/images/parks/header/park-header_disneysanimalkingdomthemepark.webp"),
			disneyshollywoodstudios: require("../../assets/images/parks/header/park-header_disneyshollywoodstudios.webp"),
			djurssommerland: require("../../assets/images/parks/header/park-header_djurssommerland.webp"),
			efteling: require("../../assets/images/parks/header/park-header_efteling.webp"),
			energylandia: require("../../assets/images/parks/header/park-header_energylandia.webp"),
			epcot: require("../../assets/images/parks/header/park-header_epcot.webp"),
			europapark: require("../../assets/images/parks/header/park-header_europapark.webp"),
			familypark: require("../../assets/images/parks/header/park-header_familypark.webp"),
			ferrariland: require("../../assets/images/parks/header/park-header_ferrariland.webp"),
			futuroscope: require("../../assets/images/parks/header/park-header_futuroscope.webp"),
			gardaland: require("../../assets/images/parks/header/park-header_gardaland.webp"),
			hansapark: require("../../assets/images/parks/header/park-header_hansapark.webp"),
			heidepark: require("../../assets/images/parks/header/park-header_heidepark.webp"),
			holidaypark: require("../../assets/images/parks/header/park-header_holidaypark.webp"),
			legoland: require("../../assets/images/parks/header/park-header_legoland.webp"),
			legolandbillund: require("../../assets/images/parks/header/park-header_legolandbillund.webp"),
			legolandcalifornia: require("../../assets/images/parks/header/park-header_legolandcalifornia.webp"),
			legolandflorida: require("../../assets/images/parks/header/park-header_legolandflorida.webp"),
			legolandnewyork: require("../../assets/images/parks/header/park-header_legolandnewyork.webp"),
			legolandwindsor: require("../../assets/images/parks/header/park-header_legolandwindsor.webp"),
			liseberg: require("../../assets/images/parks/header/park-header_liseberg.webp"),
			magickingdompark: require("../../assets/images/parks/header/park-header_magickingdompark.webp"),
			movieparkgermany: require("../../assets/images/parks/header/park-header_movieparkgermany.webp"),
			nigloland: require("../../assets/images/parks/header/park-header_nigloland.webp"),
			parcasterix: require("../../assets/images/parks/header/park-header_parcasterix.webp"),
			phantasialand: require("../../assets/images/parks/header/park-header_phantasialand.webp"),
			plopsalanddepanne: require("../../assets/images/parks/header/park-header_plopsalanddepanne.webp"),
			portaventurapark: require("../../assets/images/parks/header/park-header_portaventurapark.webp"),
			rulantica: require("../../assets/images/parks/header/park-header_rulantica.webp"),
			thorpepark: require("../../assets/images/parks/header/park-header_thorpepark.webp"),
			toverland: require("../../assets/images/parks/header/park-header_toverland.webp"),
			traumatica: require("../../assets/images/parks/header/park-header_traumatica.webp"),
			universalepicuniverse: require("../../assets/images/parks/header/park-header_universalepicuniverse.webp"),
			universalislandsofadventure: require("../../assets/images/parks/header/park-header_universalislandsofadventure.webp"),
			universalstudiosflorida: require("../../assets/images/parks/header/park-header_universalstudiosflorida.webp"),
			walibibelgium: require("../../assets/images/parks/header/park-header_walibibelgium.webp"),
			walibiholland: require("../../assets/images/parks/header/park-header_walibiholland.webp"),
		};
		return headerImageMap[id] || null;
	} catch (e) {
		return null;
	}
};
